MODIFY: main 로직 구현
2021-3q-wecode-payhere-intern/go-crawling-project pull request #1
Opened 2021-07-08 02:17 UTC by BG-YU

- 요약
  -  key 분리
  - codef 분리
  - db 분리

- 상세
  -  key 분리
      - DB 정보 및 codef client_key JSON 작성
      - JSON 로드 기능 구현
  - codef 분리
      -  상품정보 수신 기능 구현
  - db 분리
      - db connector 기능 구현

2021-07-08 02:35 UTC, AhnSeongHyun requested changes

2021-07-08 02:35 UTC, AhnSeongHyun commented on key/key.go
> +
이 부분이 config 같은 역할을 하는 것이라고 보는데, key.json 파일을 두기 보다는 환경변수에서 읽어보는 방식이 나을것 같습니다. 그래서 Config 같은 struct를 만들고 main 함수에서 시작하자마자 환경변수에서 값을 읽어와서 Config struct를 만들고 시작하는게 좋을것 같습니다.

2021-07-08 02:35 UTC, AhnSeongHyun commented on codef/codef.go
> +	if datas.Result["code"] != "CF-00000" {
```go
const ERROR_CODE = "CF-00000"
```
이런식으로 상수 처리해주시면 좋을것 같습니다.

2021-07-08 02:35 UTC, AhnSeongHyun commented on codef/codef.go
> +type depositDatas struct {
```suggestion
type DepositDatas struct {
```
대문자로 써주심녀 좋을것 같습니다.

2021-07-08 02:35 UTC, AhnSeongHyun commented on codef/codef.go
> +	productURL := "/v1/kr/card/a/cardsales/deposit-list"
이 부분도 상수화 해주시면 좋을것 같습니다.

2021-07-08 02:53 UTC, szto requested changes

2021-07-08 02:53 UTC, szto commented on codef/codef.go
> +	productURL := "/v1/kr/card/a/cardsales/deposit-list"
producUrl 은 너무 일반적이어서 다른 이름으로 써 주시면 좋겠습니다.

2021-07-08 02:53 UTC, szto commented on main.go
> +
이 부분 for 문으로 돌리면 결과가 어떻게 나오냐요?
![Screenshot of Google Chrome (2021-07-08 11-52-16 AM)](https://user-images.githubusercontent.com/19988590/124854863-fde24700-dfe2-11eb-9337-741a08127e48.jpg)

p1: resPurchaseHistoryList 로 객체 가 저장되는 형태로 구현 부탁드리겠습니다.

2021-07-09 04:31 UTC, BG-YU commented on key/key.go
> +
리뷰 감사드립니다!
수정 완료하였습니다.

2021-07-09 04:31 UTC, BG-YU commented on codef/codef.go
> +	if datas.Result["code"] != "CF-00000" {
수정 완료하였습니다.

2021-07-09 04:32 UTC, BG-YU commented on codef/codef.go
> +type depositDatas struct {
수정 완료하였습니다.

2021-07-09 04:32 UTC, BG-YU commented on codef/codef.go
> +	productURL := "/v1/kr/card/a/cardsales/deposit-list"
수정 완료하였습니다.

2021-07-09 04:33 UTC, BG-YU commented on main.go
> +
리뷰 감사드립니다!
어제 가르쳐 주신 mongodb-compass로 확인 결과, 객체 단위로 저장 되는것 확인 하였습니다.

2021-07-09 04:37 UTC, AhnSeongHyun approved these changes

2021-07-09 04:53 UTC, szto commented
- 수정하실 때는 커밋을 잘라서 391e9ff ---> 이런 식으로 코드를 reply 에 붙어주시면 좋습니다.
- 컨벤션은 다움 주에 한번 말슴드리도록 할게요.

2021-07-09 07:44 UTC, merged